#ifndef GROWATT_PRIORITY_TASK_COMMON_H
#define GROWATT_PRIORITY_TASK_COMMON_H

#define TOPIC_VALUE_PRIORITY_LOAD "load"
#define TOPIC_VALUE_PRIORITY_BAT "bat"
#define TOPIC_VALUE_PRIORITY_GRID "grid"
#define TOPIC_VALUE_PRIORITY_STATUS "status"

#define PRIORITY_CONFIG_SSOC "ssoc"
#define PRIORITY_CONFIG_PR "pr"
#define PRIORITY_CONFIG_AC "ac"


#define TOPIC_SETTINGS_PRIORITY "settings/priority"

#endif